swagger: "2.0"
info:
  title: "Scala Play-framework playground"
  description: "This is the play ground to test features of Play-framework"
  version: "1.0.0"
#host: api.nejatezamin.com
schemes:
  - "http"
  - "https"
consumes:
  - application/json
produces:
  - application/json